ref: project generation
vaadin/intellij-plugin pull request #38
Opened 2024-04-25 10:00 UTC by MarcinVaadin

## Description

New Project generation instead of Module generation

2024-04-25 10:40 UTC, MarcinVaadin commented on src/main/kotlin/com/vaadin/plugin/module/VaadinPanel.kt
Most changes in this file copied from https://github.com/JetBrains/intellij-community/blob/2a49997971c83e6f195c139f15d770015a55d290/java/idea-ui/src/com/intellij/ide/starters/shared/CommonStarterInitialStep.kt#L4

2024-04-25 10:44 UTC, MarcinVaadin commented on src/main/kotlin/com/vaadin/plugin/module/VaadinProjectBuilderAdapter.kt
> +        return lastPerformedActionId.contains("NewProject", true)
Show Vaadin wizard only on New Project creation, not New Module.

2024-04-29 10:42 UTC, abdullahtellioglu requested changes
Hello world projects tab does not work. Plugin creates the project only by first section's configurations. 

https://github.com/vaadin/intellij-plugin/assets/100126447/5fc814a9-8050-43cb-a88f-fd2ad5887558

2024-04-29 10:42 UTC, abdullahtellioglu commented on src/main/kotlin/com/vaadin/plugin/module/VaadinProjectBuilderAdapter.kt
> +        return lastPerformedActionId.contains("NewProject", true)
This is OK, the new module window does not have Vaadin section

2024-04-29 12:35 UTC, MarcinVaadin commented
> Hello world projects tab does not work. Plugin creates the project only by first section's configurations.

Fixed, good catch

2024-04-30 09:19 UTC, abdullahtellioglu approved these changes
All works!

2024-04-30 09:19 UTC, merged